/**
 * Carbon engine — pure, side-effect-free domain logic for CarbonSync.
 *
 * All carbon math (scoring, streaks, transit offsets, equivalences) lives here so
 * it can be unit-tested in isolation and reused across the UI and the simulator
 * without duplication. Keeping these functions pure also keeps the React layer
 * thin and predictable.
 */

import type { TransitMode } from "../types";

/** Flat points awarded for logging any carbon-saving activity. */
export const BASE_POINTS = 25;

/** Bonus points granted per kilogram of CO2 offset. */
export const POINTS_PER_KG = 10;

/**
 * Average annual CO2 absorbed by one mature tree, expressed as the fraction used
 * to convert kilograms saved into an approximate "trees planted" equivalent.
 * (~22 kg CO2 / tree / year -> 0.045 trees per kg.)
 */
export const TREES_PER_KG = 0.045;

/** Baseline emissions of a standard petrol vehicle, in kg CO2 per km. */
export const PETROL_KG_PER_KM = 0.22;

/**
 * Per-km emissions for each low-carbon transit mode (kg CO2 / km). The offset
 * saved versus driving is `PETROL_KG_PER_KM - modeEmission`, but for simplicity
 * the simulator treats the avoided petrol emission as the saving.
 */
export const TRANSIT_MODE_OFFSET: Record<TransitMode, number> = {
  walk: 0.22, // zero-emission, full petrol offset
  bike: 0.22, // zero-emission, full petrol offset
  electric_scooter: 0.2,
  train: 0.17,
  ev: 0.13,
};

/** One day expressed in milliseconds. */
const ONE_DAY_MS = 1000 * 60 * 60 * 24;

/**
 * Calculate points awarded for an activity given the kilograms of CO2 saved.
 * Negative or non-finite savings are clamped to zero so scoring stays sane.
 */
export function calculatePoints(kgSaved: number): number {
  const safeKg = Number.isFinite(kgSaved) && kgSaved > 0 ? kgSaved : 0;
  return Math.round(BASE_POINTS + safeKg * POINTS_PER_KG);
}

/**
 * Round a kilogram value to two decimals to avoid floating point drift when
 * accumulating savings totals.
 */
export function roundKg(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return parseFloat(value.toFixed(2));
}

/**
 * Estimate the transit carbon offset (kg CO2) for a given distance and mode,
 * compared against a standard petrol vehicle. Distances <= 0 yield 0.
 */
export function calculateTransitSavings(distanceKm: number, mode: TransitMode): number {
  if (!Number.isFinite(distanceKm) || distanceKm <= 0) return 0;
  const offset = TRANSIT_MODE_OFFSET[mode] ?? PETROL_KG_PER_KM;
  return parseFloat((distanceKm * offset).toFixed(2));
}

/**
 * Convert total kilograms of CO2 saved into an approximate number of mature
 * trees' annual absorption. Always reports at least 1 tree once any saving
 * exists, matching the dashboard's encouraging framing.
 */
export function treesEquivalent(totalSavedKg: number): number {
  if (!Number.isFinite(totalSavedKg) || totalSavedKg <= 0) return 0;
  return Math.max(1, parseFloat((totalSavedKg * TREES_PER_KG).toFixed(1)));
}

/**
 * Format a YYYY-MM-DD date string from a Date (defaults to now). Centralized so
 * the whole app derives "today" consistently.
 */
export function toDateKey(date: Date = new Date()): string {
  return date.toISOString().split("T")[0];
}

/**
 * Compute the next streak count when an activity is logged.
 *
 * - Same calendar day as last activity: streak is unchanged.
 * - Exactly the following day: streak increments by one.
 * - Any larger gap (or no prior activity): streak resets to one.
 */
export function nextStreak(
  currentStreak: number,
  lastActiveDate: string | null | undefined,
  today: string = toDateKey()
): number {
  const safeStreak = Number.isFinite(currentStreak) && currentStreak > 0 ? currentStreak : 0;

  if (!lastActiveDate) return 1;
  if (lastActiveDate === today) return Math.max(1, safeStreak);

  const yesterday = toDateKey(new Date(new Date(today).getTime() - ONE_DAY_MS));
  if (lastActiveDate === yesterday) return safeStreak + 1;

  return 1;
}

/**
 * Determine whether a streak is still valid on login, or has been broken by an
 * inactivity gap of more than one day. Returns the streak that should be stored.
 */
export function resolveStreakOnLogin(
  storedStreak: number,
  lastActiveDate: string | null | undefined,
  today: string = toDateKey()
): number {
  if (!lastActiveDate) return Math.max(1, storedStreak);
  const diffDays = Math.ceil((new Date(today).getTime() - new Date(lastActiveDate).getTime()) / ONE_DAY_MS);
  return diffDays > 1 ? 1 : Math.max(1, storedStreak);
}

/**
 * Resolve the carbon offset (kg CO2) generated by a smart meter tick where solar
 * yield may exceed household load. Excess clean energy is rewarded; a deficit
 * produces zero savings.
 */
export function smartMeterOffset(solarKw: number, loadKw: number, factor = 0.05): number {
  if (!Number.isFinite(solarKw) || !Number.isFinite(loadKw)) return 0;
  const excess = solarKw - loadKw;
  if (excess <= 0) return 0;
  return parseFloat((excess * factor).toFixed(3));
}
